module audio_soc_top (
    input  logic clk,        // Global System Clock (Drives CPU pipeline & peripheral registers)
    input  logic rst_n,      // Global Active-Low Reset (Clears state registers asynchronously)
    output logic audio_out   // Final physical pin output carrying the 1-bit PWM audio signal
);

    // =========================================================================
    // 1. INTERNAL CPU INTERCONNECT WIRES
    // These wires mirror the internal states of the CPU execution pipeline.
    // =========================================================================
    logic [31:0] pc_curr;     // Current Program Counter: Points to the instruction being fetched
    logic [31:0] pc_next;     // Next Program Counter: Calculated target address for the next clock cycle
    logic [31:0] instr;       // Instruction Bus: Carries the raw 32-bit machine code from memory to CPU decoder
    logic [31:0] alu_result;  // ALU Output: Holds calculated math results OR memory target addresses
    logic [31:0] read_data2;  // Source Register 2 Data: Holds the raw payload data to be written to memory/I/O
    logic        mem_we;      // Memory Write Enable: Master strobe active high when CPU executes a store instruction (e.g., sw)
    
    // --- Interrupt Control Signals ---
    logic        irq_signal;  // Interrupt Request: High-priority signal generated by the timer to interrupt the CPU
    logic [31:0] mepc_val;    // Machine Exception Program Counter: Holds the return address after handling an interrupt


    // =========================================================================
    // 2. AXI4-LITE BUS SIGNALS
    // Standardized channel wires replacing raw point-to-point connections.
    // =========================================================================
    
    // --- Write Address Channel (AW) ---
    // Broadcasts the target destination address from the Manager (CPU) to the Subordinates.
    logic [31:0] m_axi_awaddr;   // Write Address: Specifies which register mailbox is being targeted
    logic        m_axi_awvalid;  // Write Address Valid: High when the Manager guarantees the address wire has valid data
    logic        m_axi_awready;  // Write Address Ready: Driven by peripheral when it is free to accept the address

    // --- Write Data Channel (W) ---
    // Transmits the payload data word from the Manager (CPU) to the Subordinate.
    logic [31:0] m_axi_wdata;    // Write Data: The actual data word (e.g., the 8-bit digital sound sample)
    logic        m_axi_wvalid;   // Write Data Valid: High when the Manager guarantees the payload data wire is stable
    logic        m_axi_wready;   // Write Data Ready: Driven by peripheral when it is ready to capture the data

    // --- Write Response Channel (B) ---
    // Allows the Subordinate peripheral to confirm transaction completion back to the CPU.
    logic [1:0]  m_axi_bresp;    // Write Response: Status code (2'b00 = OKAY, 2'b01 = EXOKAY, 2'b10 = SLVERR, 2'b11 = DECERR)
    logic        m_axi_bvalid;   // Write Response Valid: Driven high by peripheral when transaction status is ready
    logic        m_axi_bready;   // Write Response Ready: Driven high by CPU to signal it has logged the status report


    // =========================================================================
    // 3. THE HARDWARE AXI-LITE BRIDGE LOGIC
    // This combinational block bridges the gap between raw CPU signals and the 
    // structured AXI protocol, preventing the synthesizer from pruning the core.
    // =========================================================================
    
    // Direct Assignments: Map raw CPU outputs straight to the AXI address and data channels
    assign m_axi_awaddr  = alu_result; // The destination address comes directly from the CPU's ALU calculation
    assign m_axi_wdata   = read_data2;  // The actual data payload comes directly from the CPU's register file output

    // Handshake Control Logic:
    // A write transaction is marked VALID if and only if the CPU core is actively firing 
    // its master Write Enable (mem_we) AND the calculated address matches the Audio Mailbox (0x400).
    assign m_axi_awvalid = (mem_we && (alu_result == 32'h400));
    assign m_axi_wvalid  = (mem_we && (alu_result == 32'h400));

    // Response Acknowledge:
    // In this basic SoC layout, the CPU core is configured to be instantly ready (`1'b1`) 
    // to accept the transaction success handshake back from the audio peripheral.
    assign m_axi_bready  = 1'b1;


    // =========================================================================
    // 4. CORE PROCESSING BLOCKS
    // The computational foundation of the System-on-Chip.
    // =========================================================================

    // --- RV32IM CPU Core (The Central Engine) ---
    // This block represents the main CPU processor containing the decoder, 
    // the 32x32 register file, and the physical single-cycle hardware multiplier.
    rv32im_core u_core (
        .clk(clk),                  // Connects master clock to step the execution pipeline
        .rst_n(rst_n),              // Connects master reset to clear registers on boot
        .instr_i(instr),            // Feed-forward path for the fetched machine code instruction
        .alu_result_o(alu_result),  // Outbound port driving memory mappings and arithmetic values
        .wdata_o(read_data2),      // Outbound port feeding register payloads to the peripherals
        .mem_we_o(mem_we)           // Master write strobe indicating active memory store operations
    );

    // --- Program Counter (The System Heartbeat) ---
    // Manages the sequential flow of execution and immediately forces vectors 
    // to handle high-priority interrupt signals generated by hardware.
    pc u_pc (
        .clk(clk), 
        .rst_n(rst_n), 
        .d(pc_next),       // Feeds back the target destination address calculated at the end of the cycle
        .q(pc_curr),       // Latches out the stable, verified address currently being fetched
        .irq(irq_signal),  // Inbound hardware flag forcing execution branch to service routine
        .mepc(mepc_val)    // Outbound register tracking original position to resume post-ISR
    );

    // --- Instruction Memory (The Firmware Code Space) ---
    // A read-only lookup block containing the compiled assembly software program.
    instr_mem u_imem (
        .addr(pc_curr),    // Addresses memory block using the stable Program Counter output
        .instr(instr)      // Flashes out the corresponding 32-bit machine language command word
    );


    // =========================================================================
    // 5. MEMORY-MAPPED PERIPHERALS
    // Subordinate functional hardware components connected to the system bus.
    // =========================================================================

    // --- Programmable Timer (Mapped to Address Space: 0x500) ---
    // Acts as a hardware metronome. When the internal countdown matches the interval value, 
    // it pulses the interrupt signal to keep audio synthesis timing mathematically locked.
    // This component is left as a raw MMIO peripheral to showcase structural bus contrast.
    timer u_timer (
        .clk(clk),
        .rst_n(rst_n),
        .we_i(mem_we && (alu_result == 32'h500)), // Enables register modification only at address 0x500
        .wdata_i(read_data2),                     // Configuration value payload defining clock tick intervals
        .irq(irq_signal)                          // Outbound physical wire driving the CPU's interrupt pin
    );

    // --- Audio Peripheral (Mapped to Address Space: 0x400 - Upgraded to AXI4-Lite) ---
    // Captures digital data chunks via the handshake protocol, translating 
    // raw values into a hardware duty cycle stream for physical audio output.
    audio_pwm_axi u_audio (
        .clk(clk),
        .rst_n(rst_n),
        // Write Address Channel Handshaking
        .s_axi_awaddr(m_axi_awaddr),
        .s_axi_awvalid(m_axi_awvalid),
        .s_axi_awready(m_axi_awready),
        // Write Data Channel Handshaking
        .s_axi_wdata(m_axi_wdata),
        .s_axi_wvalid(m_axi_wvalid),
        .s_axi_wready(m_axi_wready),
        // Status Response Channel Handshaking
        .s_axi_bresp(m_axi_bresp),
        .s_axi_bvalid(m_axi_bvalid),
        .s_axi_bready(m_axi_bready),
        // Physical Waveform Generation Output Pin
        .audio_out(audio_out)
    );


    // =========================================================================
    // 6. NEXT PROGRAM COUNTER COMBINATIONAL LOGIC
    // Computes where the execution stream travels next during standard operations.
    // =========================================================================
    // Increments the program counter sequentially by exactly 4 bytes (32 bits) per cycle.
    // Note: Complex jumps and branching metrics are processed natively within the u_pc module.
    assign pc_next = pc_curr + 4;

endmodule