/* Generated by Yosys 0.30+48 (git sha1 14d50a176d5, gcc 8.3.1 -fPIC -Os) */

module audio_soc_top(clk, rst_n, audio_out);
  output audio_out;
  wire audio_out;
  input clk;
  wire clk;
  input rst_n;
  wire rst_n;
  sky130_fd_sc_hd__conb_1 _0_ (
    .LO(audio_out)
  );
endmodule
